# Generated by Django 5.2 on 2025-04-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_product_public', 'Can view product as public'), ('add_product_user', 'Can add product as user')]},
        ),
    ]
