# Generated by Django 5.2 on 2025-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_module', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deskripsi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
