# Generated by Django 5.2 on 2025-04-22 02:13

from django.db import migrations, models

def add_initial_modules(apps, schema_editor):
    # Ambil model yang sesuai
    Module = apps.get_model('modular_engine', 'Module')

    # Tambahkan data
    Module.objects.create(name='sample_module', version='1.0.0', installed=False)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('installed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(add_initial_modules),
    ]
